name: pareezsalonapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  modal_progress_hud: ^0.1.3
  cloud_firestore: ^0.13.5
  url_launcher: ^5.5.0
  google_sign_in: ^4.5.3
  flutter_signin_button: ^1.0.0
  carousel_pro: ^1.0.0
  gender_selection: ^1.0.0
  date_picker_timeline: ^1.2.1
  day_night_time_picker: ^0.2.1
  badges: ^1.1.1
  mailer: ^3.0.4
  toast: ^0.1.5
  flutter_dotenv: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: KaushanScript
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

  assets:
    - assets/
    - .env

