name: pareezsalonapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.2
  firebase_auth: ^0.16.0
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^2.0.0
  cloud_firestore: ^0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: KaushanScript
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

  assets:
    - assets/

